baseurl: "/Fan-Trove" # หากโปรเจกต์ของคุณอยู่ใน subdirectory
url: "https://jeffy2600ii.github.io" # เปลี่ยนเป็น URL ที่ใช้กับ GitHub Pages ของคุณ

# การตั้งค่าภาษา
locales:
  en: "/en/"
  th: "/th/"

# ตรงนี้จะทำให้ระบบเข้าใจว่าเรามีสองภาษา
plugins:
  - jekyll-multiple-languages-plugin